# Generated by Django 4.2.7 on 2025-10-13 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_name", models.CharField(max_length=255)),
                ("template_name", models.CharField(max_length=255)),
                ("template_id", models.CharField(max_length=255)),
                (
                    "recipients",
                    models.TextField(help_text="Comma-separated email addresses"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_emails", models.IntegerField(default=0)),
                ("successful_emails", models.IntegerField(default=0)),
                ("failed_emails", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Campaign",
                "verbose_name_plural": "Email Campaigns",
                "ordering": ["-created_at"],
            },
        ),
    ]
