# Generated by Django 4.2.7 on 2025-10-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="deliverable_emails",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated deliverable email addresses",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="undeliverable_emails",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated undeliverable email addresses",
                null=True,
            ),
        ),
    ]
