# Generated by Django 4.2+

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_id', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(help_text='WhatsApp mobile number with country code', max_length=20)),
                ('scheduled_time', models.DateTimeField(help_text='When to send the message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Actual time when message was sent', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Campaign',
                'verbose_name_plural': 'WhatsApp Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]

